services:
  - type: web
    name: sales-insight-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        generateValue: true
